import argparse
from collections import defaultdict
import copy
import json
from pathlib import Path
import datasets

# these dictionaries come from dataset_stats.py

# all 395 unique codes parsed from from bloom_downloads text fields
_BLOOM_LANGUAGES = {
    "kwd",
    "lo",
    "sps",
    "cry",
    "wms",
    "prs",
    "gwc",
    "bfn",
    "kms",
    "oki",
    "quf",
    "wni",
    "ceb-x-boholano",
    "laj",
    "kyq",
    "or",
    "rue",
    "mve",
    "gsw",
    "ru-KG",
    "ken",
    "ekm",
    "tn",
    "sw",
    "swh",
    "tdt",
    "my",
    "kmr",
    "syw",
    "xog",
    "ksw",
    "pcg",
    "guz",
    "khb",
    "clo",
    "bob",
    "pbt",
    "teo",
    "kxp",
    "tet",
    "ts",
    "ha",
    "ve",
    "mxu",
    "es-PE",
    "de",
    "cmo",
    "am",
    "bef",
    "bn",
    "ro",
    "bzi",
    "ml",
    "af",
    "mzm",
    "yas",
    "bec",
    "awa",
    "bkm",
    "so",
    "tnn",
    "the",
    "ann",
    "myx",
    "ddg",
    "yet",
    "hbb",
    "adq",
    "sok",
    "bfm",
    "bra",
    "csw-Cans-CA",
    "ilo",
    "lhm",
    "rug",
    "lmp",
    "mnf",
    "tdb",
    "ada",
    "tvs",
    "th",
    "wbr",
    "dtp",
    "pnz",
    "sea",
    "brv",
    "xmg",
    "saq-x-Ilchamus",
    "sa",
    "mne",
    "lwl",
    "dty",
    "chd",
    "lg",
    "vif",
    "lkb",
    "fuv-Arab",
    "ded",
    "nsk",
    "fub",
    "mhx",
    "pa",
    "isu",
    "bjn",
    "tl",
    "ht",
    "boz",
    "zgh",
    "enb-x-Sengwer",
    "bxa",
    "qub",
    "hla",
    "jgo",
    "taj",
    "ajz",
    "kmu",
    "psp",
    "xmm",
    "shn",
    "zuh",
    "cim",
    "lan",
    "st",
    "lfa",
    "es",
    "tio",
    "mdr",
    "ydd",
    "fil",
    "nod",
    "id",
    "csw-Latn",
    "bhs",
    "udg",
    "gou",
    "hre",
    "ahk",
    "bi",
    "qvh",
    "mfj",
    "miy",
    "mgm",
    "ybh",
    "ymp",
    "es-GT",
    "fal",
    "pex",
    "bfd",
    "zh",
    "pwg",
    "bgf",
    "omw",
    "dtr",
    "ku",
    "cak",
    "ky",
    "sgd",
    "quc",
    "cuh",
    "eee",
    "bze",
    "bo",
    "jmx-x-smp",
    "new",
    "dig",
    "gu",
    "dug",
    "pag",
    "aaa",
    "bag",
    "oj",
    "ngn",
    "ny",
    "zlm",
    "kbq",
    "baw",
    "ak",
    "mot",
    "jmx",
    "amu",
    "ta",
    "tg",
    "nlv",
    "aph",
    "mlk",
    "en-Brai-IN-x-Chetana-Trust",
    "dje",
    "nyu",
    "tnl",
    "xkg",
    "gbj",
    "snk-Arab",
    "ino",
    "sox",
    "tpu",
    "bya",
    "pmf",
    "krr",
    "nuj",
    "kn",
    "ne",
    "mgg",
    "pkb",
    "snl",
    "mgo",
    "km",
    "kmg",
    "mkz",
    "bkc",
    "pea",
    "mnw",
    "msb",
    "lhu",
    "tpl",
    "ybi",
    "bqm",
    "uz",
    "zu",
    "hi",
    "kwx",
    "ike",
    "njy",
    "yav",
    "nge",
    "nxa",
    "nxl",
    "ybb",
    "en-Dupl",
    "tdc",
    "bcc",
    "jmx-x-EnAm",
    "kbx",
    "chp",
    "rme",
    "pis",
    "snk",
    "sdk",
    "abc",
    "zaw",
    "mle",
    "kby",
    "nsk-Latn",
    "ceb",
    "bbk",
    "hro",
    "kvt",
    "tnp",
    "kak",
    "nwi",
    "th-TH",
    "xh",
    "lbr",
    "fon",
    "dag",
    "bim",
    "qve",
    "vi",
    "wnk",
    "mqj",
    "ags",
    "nsp",
    "ur",
    "lgr",
    "war",
    "pt",
    "lgg",
    "loh",
    "tnt",
    "cgc",
    "thy",
    "luy",
    "aeu",
    "kek",
    "tdg",
    "sml",
    "tkd",
    "sat",
    "nso",
    "bce",
    "dmg",
    "bjr",
    "hil",
    "gal",
    "fr",
    "ssn",
    "saq",
    "mr",
    "gwc-Arab",
    "ame",
    "ki",
    "hig",
    "myk",
    "qvm",
    "pdu",
    "sor",
    "enc",
    "nsn",
    "mlw",
    "ja",
    "en-IN",
    "mry",
    "nco",
    "bss",
    "fli",
    "nza",
    "stk",
    "bwt",
    "yi",
    "roo",
    "csw",
    "kr",
    "rel",
    "en",
    "mrn",
    "amp",
    "nwe",
    "kqr",
    "kjb",
    "hna",
    "xmd",
    "mai",
    "lts",
    "bho",
    "jra",
    "jmx-x-coi",
    "zh-CN",
    "qvo",
    "cuv",
    "bkh",
    "mmu",
    "rw",
    "agq",
    "wbm",
    "kam",
    "buo",
    "bud",
    "azn",
    "yea",
    "mgq",
    "cmn",
    "pae",
    "bri",
    "bkx",
    "idt",
    "mfh",
    "lsi",
    "xty",
    "cbr",
    "tsb",
    "brb",
    "guc",
    "qxh",
    "fuh",
    "pce",
    "tuv",
    "awb",
    "mam",
    "nst",
    "bm",
    "hao",
    "nla",
    "wtk",
    "odk",
    "tom",
    "thl",
    "tuz",
    "ewo",
    "azo",
    "aia",
    "dnw",
    "tpi",
    "nyo",
    "nas",
    "llg",
    "mxl",
    "tbj",
    "muv",
    "lns",
    "qaa",
    "bwx",
    "ko",
    "yin",
    "nhx",
    "sxb",
    "kwu",
    "ru",
    "it",
    "rnl",
    "tod",
    "thk",
    "unr",
    "nl",
    "ozm",
    "bax",
    "quz",
}

# dictionary to convert from original language codes to alpha3. There's 395 entries
_BLOOM_LANGUAGES_ALPHA3_CONVERSION_DICT = {
    "kwd": "kwd",
    "lo": "lao",
    "sps": "sps",
    "cry": "cry",
    "wms": "wms",
    "prs": "fas",
    "gwc": "gwc",
    "bfn": "bfn",
    "kms": "kms",
    "oki": "oki",
    "quf": "quf",
    "wni": "wni",
    "ceb-x-boholano": "ceb",
    "laj": "laj",
    "kyq": "kyq",
    "or": "ori",
    "rue": "rue",
    "mve": "mve",
    "gsw": "gsw",
    "ru-KG": "rus",
    "ken": "ken",
    "ekm": "ekm",
    "tn": "tsn",
    "sw": "swa",
    "swh": "swh",
    "tdt": "tdt",
    "my": "mya",
    "kmr": "kmr",
    "syw": "syw",
    "xog": "xog",
    "ksw": "ksw",
    "pcg": "pcg",
    "guz": "guz",
    "khb": "khb",
    "clo": "clo",
    "bob": "bob",
    "pbt": "pbt",
    "teo": "teo",
    "kxp": "kxp",
    "tet": "tet",
    "ts": "tso",
    "ha": "hau",
    "ve": "ven",
    "mxu": "mxu",
    "es-PE": "spa",
    "de": "deu",
    "cmo": "cmo",
    "am": "amh",
    "bef": "bef",
    "bn": "ben",
    "ro": "ron",
    "bzi": "bzi",
    "ml": "mal",
    "af": "afr",
    "mzm": "mzm",
    "yas": "yas",
    "bec": "bec",
    "awa": "awa",
    "bkm": "bkm",
    "so": "som",
    "tnn": "tnn",
    "the": "the",
    "ann": "ann",
    "myx": "myx",
    "ddg": "ddg",
    "yet": "yet",
    "hbb": "hbb",
    "adq": "adq",
    "sok": "sok",
    "bfm": "bfm",
    "bra": "bra",
    "csw-Cans-CA": "csw",
    "ilo": "ilo",
    "lhm": "lhm",
    "rug": "rug",
    "lmp": "lmp",
    "mnf": "mnf",
    "tdb": "tdb",
    "ada": "ada",
    "tvs": "tvs",
    "th": "tha",
    "wbr": "wbr",
    "dtp": "dtp",
    "pnz": "pnz",
    "sea": "sea",
    "brv": "brv",
    "xmg": "xmg",
    "saq-x-Ilchamus": "saq",
    "sa": "san",
    "mne": "mne",
    "lwl": "lwl",
    "dty": "dty",
    "chd": "chd",
    "lg": "lug",
    "vif": "vif",
    "lkb": "lkb",
    "fuv-Arab": "fuv",
    "ded": "ded",
    "nsk": "nsk",
    "fub": "fub",
    "mhx": "mhx",
    "pa": "pan",
    "isu": "isu",
    "bjn": "bjn",
    "tl": "fil",
    "ht": "hat",
    "boz": "boz",
    "zgh": "zgh",
    "enb-x-Sengwer": "enb",
    "bxa": "bxa",
    "qub": "qub",
    "hla": "hla",
    "jgo": "jgo",
    "taj": "taj",
    "ajz": "ajz",
    "kmu": "kmu",
    "psp": "psp",
    "xmm": "xmm",
    "shn": "shn",
    "zuh": "zuh",
    "cim": "cim",
    "lan": "lan",
    "st": "sot",
    "lfa": "lfa",
    "es": "spa",
    "tio": "tio",
    "mdr": "mdr",
    "ydd": "ydd",
    "fil": "fil",
    "nod": "nod",
    "id": "ind",
    "csw-Latn": "csw",
    "bhs": "bhs",
    "udg": "udg",
    "gou": "gou",
    "hre": "hre",
    "ahk": "ahk",
    "bi": "bis",
    "qvh": "qvh",
    "mfj": "mfj",
    "miy": "miy",
    "mgm": "mgm",
    "ybh": "ybh",
    "ymp": "ymp",
    "es-GT": "spa",
    "fal": "fal",
    "pex": "pex",
    "bfd": "bfd",
    "zh": "zho",
    "pwg": "pwg",
    "bgf": "bgf",
    "omw": "omw",
    "dtr": "dtr",
    "ku": "kur",
    "cak": "cak",
    "ky": "kir",
    "sgd": "sgd",
    "quc": "quc",
    "cuh": "cuh",
    "eee": "eee",
    "bze": "bze",
    "bo": "bod",
    "jmx-x-smp": "jmx",
    "new": "new",
    "dig": "dig",
    "gu": "guj",
    "dug": "dug",
    "pag": "pag",
    "aaa": "aaa",
    "bag": "bag",
    "oj": "oji",
    "ngn": "ngn",
    "ny": "nya",
    "zlm": "zlm",
    "kbq": "kbq",
    "baw": "baw",
    "ak": "aka",
    "mot": "mot",
    "jmx": "jmx",
    "amu": "amu",
    "ta": "tam",
    "tg": "tgk",
    "nlv": "nlv",
    "aph": "aph",
    "mlk": "mlk",
    "en-Brai-IN-x-Chetana-Trust": "eng",
    "dje": "dje",
    "nyu": "nyu",
    "tnl": "tnl",
    "xkg": "xkg",
    "gbj": "gbj",
    "snk-Arab": "snk",
    "ino": "ino",
    "sox": "sox",
    "tpu": "tpu",
    "bya": "bya",
    "pmf": "pmf",
    "krr": "krr",
    "nuj": "nuj",
    "kn": "kan",
    "ne": "nep",
    "mgg": "mgg",
    "pkb": "pkb",
    "snl": "snl",
    "mgo": "mgo",
    "km": "khm",
    "kmg": "kmg",
    "mkz": "mkz",
    "bkc": "bkc",
    "pea": "pea",
    "mnw": "mnw",
    "msb": "msb",
    "lhu": "lhu",
    "tpl": "tpl",
    "ybi": "ybi",
    "bqm": "bqm",
    "uz": "uzb",
    "zu": "zul",
    "hi": "hin",
    "kwx": "kwx",
    "ike": "ike",
    "njy": "njy",
    "yav": "yav",
    "nge": "nge",
    "nxa": "nxa",
    "nxl": "nxl",
    "ybb": "ybb",
    "en-Dupl": "eng",
    "tdc": "tdc",
    "bcc": "bcc",
    "jmx-x-EnAm": "jmx",
    "kbx": "kbx",
    "chp": "chp",
    "rme": "rme",
    "pis": "pis",
    "snk": "snk",
    "sdk": "sdk",
    "abc": "abc",
    "zaw": "zaw",
    "mle": "mle",
    "kby": "kby",
    "nsk-Latn": "nsk",
    "ceb": "ceb",
    "bbk": "bbk",
    "hro": "hro",
    "kvt": "kvt",
    "tnp": "tnp",
    "kak": "kak",
    "nwi": "nwi",
    "th-TH": "tha",
    "xh": "xho",
    "lbr": "lbr",
    "fon": "fon",
    "dag": "dag",
    "bim": "bim",
    "qve": "qve",
    "vi": "vie",
    "wnk": "wnk",
    "mqj": "mqj",
    "ags": "ags",
    "nsp": "nsp",
    "ur": "urd",
    "lgr": "lgr",
    "war": "war",
    "pt": "por",
    "lgg": "lgg",
    "loh": "loh",
    "tnt": "tnt",
    "cgc": "cgc",
    "thy": "thy",
    "luy": "luy",
    "aeu": "aeu",
    "kek": "kek",
    "tdg": "tdg",
    "sml": "sml",
    "tkd": "tkd",
    "sat": "sat",
    "nso": "nso",
    "bce": "bce",
    "dmg": "dmg",
    "bjr": "bjr",
    "hil": "hil",
    "gal": "gal",
    "fr": "fra",
    "ssn": "ssn",
    "saq": "saq",
    "mr": "mar",
    "gwc-Arab": "gwc",
    "ame": "ame",
    "ki": "kik",
    "hig": "hig",
    "myk": "myk",
    "qvm": "qvm",
    "pdu": "pdu",
    "sor": "sor",
    "enc": "enc",
    "nsn": "nsn",
    "mlw": "mlw",
    "ja": "jpn",
    "en-IN": "eng",
    "mry": "mry",
    "nco": "nco",
    "bss": "bss",
    "fli": "fli",
    "nza": "nza",
    "stk": "stk",
    "bwt": "bwt",
    "yi": "yid",
    "roo": "roo",
    "csw": "csw",
    "kr": "kau",
    "rel": "rel",
    "en": "eng",
    "mrn": "mrn",
    "amp": "amp",
    "nwe": "nwe",
    "kqr": "kqr",
    "kjb": "kjb",
    "hna": "hna",
    "xmd": "xmd",
    "mai": "mai",
    "lts": "lts",
    "bho": "bho",
    "jra": "jra",
    "jmx-x-coi": "jmx",
    "zh-CN": "zho",
    "qvo": "qvo",
    "cuv": "cuv",
    "bkh": "bkh",
    "mmu": "mmu",
    "rw": "kin",
    "agq": "agq",
    "wbm": "wbm",
    "kam": "kam",
    "buo": "buo",
    "bud": "bud",
    "azn": "azn",
    "yea": "yea",
    "mgq": "mgq",
    "cmn": "cmn",
    "pae": "pae",
    "bri": "bri",
    "bkx": "bkx",
    "idt": "idt",
    "mfh": "mfh",
    "lsi": "lsi",
    "xty": "xty",
    "cbr": "cbr",
    "tsb": "tsb",
    "brb": "brb",
    "guc": "guc",
    "qxh": "qxh",
    "fuh": "fuh",
    "pce": "pce",
    "tuv": "tuv",
    "awb": "awb",
    "mam": "mam",
    "nst": "nst",
    "bm": "bam",
    "hao": "hao",
    "nla": "nla",
    "wtk": "wtk",
    "odk": "odk",
    "tom": "tom",
    "thl": "thl",
    "tuz": "tuz",
    "ewo": "ewo",
    "azo": "azo",
    "aia": "aia",
    "dnw": "dnw",
    "tpi": "tpi",
    "nyo": "nyo",
    "nas": "nas",
    "llg": "llg",
    "mxl": "mxl",
    "tbj": "tbj",
    "muv": "muv",
    "lns": "lns",
    "qaa": "qaa",
    "bwx": "bwx",
    "ko": "kor",
    "yin": "yin",
    "nhx": "nhx",
    "sxb": "sxb",
    "kwu": "kwu",
    "ru": "rus",
    "it": "ita",
    "rnl": "rnl",
    "tod": "tod",
    "thk": "thk",
    "unr": "unr",
    "nl": "nld",
    "ozm": "ozm",
    "bax": "bax",
    "quz": "quz",
}

# display names, natural language. Calculated using langcodes library from alpha3 codes
_BLOOM_LANGUAGES_ALPHA3_DISPLAY_NAMES = {
    "kwd": "Kwaio",
    "lao": "Lao",
    "sps": "Saposa",
    "cry": "Cori",
    "wms": "Wambon",
    "fas": "Persian (Afghanistan)",
    "gwc": "Gawri (Arabic)",
    "bfn": "Bunak",
    "kms": "Kamasau",
    "oki": "Okiek",
    "quf": "Lambayeque Quechua",
    "wni": "Ndzwani Comorian",
    "ceb": "Cebuano",
    "laj": "Lango (Uganda)",
    "kyq": "Kenga",
    "ori": "Odia",
    "rue": "Rusyn",
    "mve": "Marwari (Pakistan)",
    "gsw": "Swiss German",
    "rus": "Russian",
    "ken": "Kenyang",
    "ekm": "Elip",
    "tsn": "Tswana",
    "swa": "Swahili",
    "swh": "Swahili (individual language)",
    "tdt": "Tetun Dili",
    "mya": "Burmese",
    "kmr": "Northern Kurdish",
    "syw": "Kagate",
    "xog": "Soga",
    "ksw": "S'gaw Karen",
    "pcg": "Paniya",
    "guz": "Gusii",
    "khb": "Lü",
    "clo": "Lowland Oaxaca Chontal",
    "bob": "Aweer",
    "pbt": "Southern Pashto",
    "teo": "Teso",
    "kxp": "Wadiyara Koli",
    "tet": "Tetum",
    "tso": "Tsonga",
    "hau": "Hausa",
    "ven": "Venda",
    "mxu": "Mada (Cameroon)",
    "spa": "Spanish (Guatemala)",
    "deu": "German",
    "cmo": "Central Mnong",
    "amh": "Amharic",
    "bef": "Benabena",
    "ben": "Bangla",
    "ron": "Romanian",
    "bzi": "Bisu",
    "mal": "Malayalam",
    "afr": "Afrikaans",
    "mzm": "Mumuye",
    "yas": "Nugunu (Cameroon)",
    "bec": "Iceve-Maci",
    "awa": "Awadhi",
    "bkm": "Kom",
    "som": "Somali",
    "tnn": "North Tanna",
    "the": "Chitwania Tharu",
    "ann": "Obolo",
    "myx": "Masaaba",
    "ddg": "Fataluku",
    "yet": "Yetfa",
    "hbb": "Huba",
    "adq": "Adangbe",
    "sok": "Sokoro",
    "bfm": "Mmen",
    "bra": "Braj",
    "csw": "Swampy Cree",
    "ilo": "Iloko",
    "lhm": "Lhomi",
    "rug": "Roviana",
    "lmp": "Limbum",
    "mnf": "Mundani",
    "tdb": "Panchpargania",
    "ada": "Adangme",
    "tvs": "Taveta",
    "tha": "Thai (Thailand)",
    "wbr": "Wagdi",
    "dtp": "Central Dusun",
    "pnz": "Pana (Central African Republic)",
    "sea": "Semai",
    "brv": "Western Bru",
    "xmg": "Mengaka",
    "saq": "Samburu",
    "san": "Sanskrit",
    "mne": "Naba",
    "lwl": "Eastern Lawa",
    "dty": "Dotyali",
    "chd": "Highland Oaxaca Chontal",
    "lug": "Ganda",
    "vif": "Vili",
    "lkb": "Kabras",
    "fuv": "Nigerian Fulfulde (Arabic)",
    "ded": "Dedua",
    "nsk": "Naskapi (Latin)",
    "fub": "Adamawa Fulfulde",
    "mhx": "Maru",
    "pan": "Punjabi",
    "isu": "Isu (Menchum Division)",
    "bjn": "Banjar",
    "fil": "Filipino",
    "hat": "Haitian Creole",
    "boz": "Tiéyaxo Bozo",
    "zgh": "Standard Moroccan Tamazight",
    "enb": "Markweeta",
    "bxa": "Tairaha",
    "qub": "Huallaga Huánuco Quechua",
    "hla": "Halia",
    "jgo": "Ngomba",
    "taj": "Eastern Tamang",
    "ajz": "Amri Karbi",
    "kmu": "Kanite",
    "psp": "Philippine Sign Language",
    "xmm": "Manado Malay",
    "shn": "Shan",
    "zuh": "Tokano",
    "cim": "Cimbrian",
    "lan": "Laru",
    "sot": "Southern Sotho",
    "lfa": "Lefa",
    "tio": "Teop",
    "mdr": "Mandar",
    "ydd": "Eastern Yiddish",
    "nod": "Northern Thai",
    "ind": "Indonesian",
    "bhs": "Buwal",
    "udg": "Muduga",
    "gou": "Gavar",
    "hre": "Hre",
    "ahk": "Akha",
    "bis": "Bislama",
    "qvh": "Huamalíes-Dos de Mayo Huánuco Quechua",
    "mfj": "Mefele",
    "miy": "Ayutla Mixtec",
    "mgm": "Mambae",
    "ybh": "Yakha",
    "ymp": "Yamap",
    "fal": "South Fali",
    "pex": "Petats",
    "bfd": "Bafut",
    "zho": "Chinese (China)",
    "pwg": "Gapapaiwa",
    "bgf": "Bangandu",
    "omw": "South Tairora",
    "dtr": "Lotud",
    "kur": "Kurdish",
    "cak": "Kaqchikel",
    "kir": "Kyrgyz",
    "sgd": "Surigaonon",
    "quc": "Kʼicheʼ",
    "cuh": "Chuka",
    "eee": "E",
    "bze": "Jenaama Bozo",
    "bod": "Tibetan",
    "jmx": "Western Juxtlahuaca Mixtec",
    "new": "Newari",
    "dig": "Digo",
    "guj": "Gujarati",
    "dug": "Duruma",
    "pag": "Pangasinan",
    "aaa": "Ghotuo",
    "bag": "Tuki",
    "oji": "Ojibwa",
    "ngn": "Ngwo",
    "nya": "Nyanja",
    "zlm": "Malay (individual language)",
    "kbq": "Kamano",
    "baw": "Bambili-Bambui",
    "aka": "Akan",
    "mot": "Barí",
    "amu": "Guerrero Amuzgo",
    "tam": "Tamil",
    "tgk": "Tajik",
    "nlv": "Orizaba Nahuatl",
    "aph": "Athpariya",
    "mlk": "Ilwana",
    "eng": "English",
    "dje": "Zarma",
    "nyu": "Nyungwe",
    "tnl": "Lenakel",
    "xkg": "Kagoro",
    "gbj": "Bodo Gadaba",
    "snk": "Soninke",
    "ino": "Inoke-Yate",
    "sox": "Swo",
    "tpu": "Tampuan",
    "bya": "Batak",
    "pmf": "Pamona",
    "krr": "Krung",
    "nuj": "Nyole",
    "kan": "Kannada",
    "nep": "Nepali",
    "mgg": "Mpumpong",
    "pkb": "Pokomo",
    "snl": "Sangil",
    "mgo": "Metaʼ",
    "khm": "Khmer",
    "kmg": "Kâte",
    "mkz": "Makasae",
    "bkc": "Baka (Cameroon)",
    "pea": "Peranakan Indonesian",
    "mnw": "Mon",
    "msb": "Masbatenyo",
    "lhu": "Lahu",
    "tpl": "Tlacoapa Me'phaa",
    "ybi": "Yamphu",
    "bqm": "Wumboko",
    "uzb": "Uzbek",
    "zul": "Zulu",
    "hin": "Hindi",
    "kwx": "Khirwar",
    "ike": "Eastern Canadian Inuktitut",
    "njy": "Njyem",
    "yav": "Yangben",
    "nge": "Ngemba",
    "nxa": "Nauete",
    "nxl": "South Nuaulu",
    "ybb": "Yemba",
    "tdc": "Emberá-Tadó",
    "bcc": "Southern Balochi",
    "kbx": "Ap Ma",
    "chp": "Chipewyan",
    "rme": "Angloromani",
    "pis": "Pijin",
    "sdk": "Sos Kundi",
    "abc": "Ambala Ayta",
    "zaw": "Mitla Zapotec",
    "mle": "Manambu",
    "kby": "Manga Kanuri",
    "bbk": "Babanki",
    "hro": "Haroi",
    "kvt": "Lahta Karen",
    "tnp": "Whitesands",
    "kak": "Kalanguya",
    "nwi": "Southwest Tanna",
    "xho": "Xhosa",
    "lbr": "Lohorung",
    "fon": "Fon",
    "dag": "Dagbani",
    "bim": "Bimoba",
    "qve": "Eastern Apurímac Quechua",
    "vie": "Vietnamese",
    "wnk": "Wanukaka",
    "mqj": "Mamasa",
    "ags": "Esimbi",
    "nsp": "Nepalese Sign Language",
    "urd": "Urdu",
    "lgr": "Lengo",
    "war": "Waray",
    "por": "Portuguese",
    "lgg": "Lugbara",
    "loh": "Narim",
    "tnt": "Tontemboan",
    "cgc": "Kagayanen",
    "thy": "Tha",
    "luy": "Luyia",
    "aeu": "Akeu",
    "kek": "Kekchí",
    "tdg": "Western Tamang",
    "sml": "Central Sama",
    "tkd": "Tukudede",
    "sat": "Santali",
    "nso": "Northern Sotho",
    "bce": "Bamenyam",
    "dmg": "Upper Kinabatangan",
    "bjr": "Binumarien",
    "hil": "Hiligaynon",
    "gal": "Galolen",
    "fra": "French",
    "ssn": "Waata",
    "mar": "Marathi",
    "ame": "Yanesha'",
    "kik": "Kikuyu",
    "hig": "Kamwe",
    "myk": "Mamara Senoufo",
    "qvm": "Margos-Yarowilca-Lauricocha Quechua",
    "pdu": "Kayan",
    "sor": "Somrai",
    "enc": "En",
    "nsn": "Nehan",
    "mlw": "Moloko",
    "jpn": "Japanese",
    "mry": "Mandaya",
    "nco": "Sibe",
    "bss": "Akoose",
    "fli": "Fali",
    "nza": "Tigon Mbembe",
    "stk": "Arammba",
    "bwt": "Bafaw-Balong",
    "yid": "Yiddish",
    "roo": "Rotokas",
    "kau": "Kanuri",
    "rel": "Rendille",
    "mrn": "Cheke Holo",
    "amp": "Alamblak",
    "nwe": "Ngwe",
    "kqr": "Kimaragang",
    "kjb": "Q'anjob'al",
    "hna": "Mina (Cameroon)",
    "xmd": "Mbudum",
    "mai": "Maithili",
    "lts": "Tachoni",
    "bho": "Bhojpuri",
    "jra": "Jarai",
    "qvo": "Napo Lowland Quechua",
    "cuv": "Cuvok",
    "bkh": "Bakoko",
    "mmu": "Mmaala",
    "kin": "Kinyarwanda",
    "agq": "Aghem",
    "wbm": "Wa",
    "kam": "Kamba",
    "buo": "Terei",
    "bud": "Ntcham",
    "azn": "Western Durango Nahuatl",
    "yea": "Ravula",
    "mgq": "Malila",
    "cmn": "Mandarin Chinese",
    "pae": "Pagibete",
    "bri": "Mokpwe",
    "bkx": "Baikeno",
    "idt": "Idaté",
    "mfh": "Matal",
    "lsi": "Lashi",
    "xty": "Yoloxochitl Mixtec",
    "cbr": "Cashibo-Cacataibo",
    "tsb": "Tsamai",
    "brb": "Lave",
    "guc": "Wayuu",
    "qxh": "Panao Huánuco Quechua",
    "fuh": "Western Niger Fulfulde",
    "pce": "Ruching Palaung",
    "tuv": "Turkana",
    "awb": "Awa (Papua New Guinea)",
    "mam": "Mam",
    "nst": "Tase Naga",
    "bam": "Bambara",
    "hao": "Hakö",
    "nla": "Ngombale",
    "wtk": "Watakataui",
    "odk": "Od",
    "tom": "Tombulu",
    "thl": "Dangaura Tharu",
    "tuz": "Turka",
    "ewo": "Ewondo",
    "azo": "Awing",
    "aia": "Arosi",
    "dnw": "Western Dani",
    "tpi": "Tok Pisin",
    "nyo": "Nyoro",
    "nas": "Naasioi",
    "llg": "Lole",
    "mxl": "Maxi Gbe",
    "tbj": "Tiang",
    "muv": "Muthuvan",
    "lns": "Lamnso'",
    "qaa": "Unknown language [qaa]",
    "bwx": "Bu-Nao Bunu",
    "kor": "Korean",
    "yin": "Riang Lai",
    "nhx": "Isthmus-Mecayapan Nahuatl",
    "sxb": "Suba",
    "kwu": "Kwakum",
    "ita": "Italian",
    "rnl": "Ranglong",
    "tod": "Toma",
    "thk": "Tharaka",
    "unr": "Mundari",
    "nld": "Dutch",
    "ozm": "Koonzime",
    "bax": "Bamun",
    "quz": "Cusco Quechua",
}

# dictionary to deconvert from alpha3 to original. Note that it's not 1 to 1!
# in this direction we've got only 376 entries
_BLOOM_LANGUAGES_ALPHA3_DECONVERSION_DICT = {
    "kwd": ["kwd"],
    "lao": ["lo"],
    "sps": ["sps"],
    "cry": ["cry"],
    "wms": ["wms"],
    "fas": ["prs"],
    "gwc": ["gwc", "gwc-Arab"],
    "bfn": ["bfn"],
    "kms": ["kms"],
    "oki": ["oki"],
    "quf": ["quf"],
    "wni": ["wni"],
    "ceb": ["ceb-x-boholano", "ceb"],
    "laj": ["laj"],
    "kyq": ["kyq"],
    "ori": ["or"],
    "rue": ["rue"],
    "mve": ["mve"],
    "gsw": ["gsw"],
    "rus": ["ru-KG", "ru"],
    "ken": ["ken"],
    "ekm": ["ekm"],
    "tsn": ["tn"],
    "swa": ["sw"],
    "swh": ["swh"],
    "tdt": ["tdt"],
    "mya": ["my"],
    "kmr": ["kmr"],
    "syw": ["syw"],
    "xog": ["xog"],
    "ksw": ["ksw"],
    "pcg": ["pcg"],
    "guz": ["guz"],
    "khb": ["khb"],
    "clo": ["clo"],
    "bob": ["bob"],
    "pbt": ["pbt"],
    "teo": ["teo"],
    "kxp": ["kxp"],
    "tet": ["tet"],
    "tso": ["ts"],
    "hau": ["ha"],
    "ven": ["ve"],
    "mxu": ["mxu"],
    "spa": ["es-PE", "es", "es-GT"],
    "deu": ["de"],
    "cmo": ["cmo"],
    "amh": ["am"],
    "bef": ["bef"],
    "ben": ["bn"],
    "ron": ["ro"],
    "bzi": ["bzi"],
    "mal": ["ml"],
    "afr": ["af"],
    "mzm": ["mzm"],
    "yas": ["yas"],
    "bec": ["bec"],
    "awa": ["awa"],
    "bkm": ["bkm"],
    "som": ["so"],
    "tnn": ["tnn"],
    "the": ["the"],
    "ann": ["ann"],
    "myx": ["myx"],
    "ddg": ["ddg"],
    "yet": ["yet"],
    "hbb": ["hbb"],
    "adq": ["adq"],
    "sok": ["sok"],
    "bfm": ["bfm"],
    "bra": ["bra"],
    "csw": ["csw-Cans-CA", "csw-Latn", "csw"],
    "ilo": ["ilo"],
    "lhm": ["lhm"],
    "rug": ["rug"],
    "lmp": ["lmp"],
    "mnf": ["mnf"],
    "tdb": ["tdb"],
    "ada": ["ada"],
    "tvs": ["tvs"],
    "tha": ["th", "th-TH"],
    "wbr": ["wbr"],
    "dtp": ["dtp"],
    "pnz": ["pnz"],
    "sea": ["sea"],
    "brv": ["brv"],
    "xmg": ["xmg"],
    "saq": ["saq-x-Ilchamus", "saq"],
    "san": ["sa"],
    "mne": ["mne"],
    "lwl": ["lwl"],
    "dty": ["dty"],
    "chd": ["chd"],
    "lug": ["lg"],
    "vif": ["vif"],
    "lkb": ["lkb"],
    "fuv": ["fuv-Arab"],
    "ded": ["ded"],
    "nsk": ["nsk", "nsk-Latn"],
    "fub": ["fub"],
    "mhx": ["mhx"],
    "pan": ["pa"],
    "isu": ["isu"],
    "bjn": ["bjn"],
    "fil": ["tl", "fil"],
    "hat": ["ht"],
    "boz": ["boz"],
    "zgh": ["zgh"],
    "enb": ["enb-x-Sengwer"],
    "bxa": ["bxa"],
    "qub": ["qub"],
    "hla": ["hla"],
    "jgo": ["jgo"],
    "taj": ["taj"],
    "ajz": ["ajz"],
    "kmu": ["kmu"],
    "psp": ["psp"],
    "xmm": ["xmm"],
    "shn": ["shn"],
    "zuh": ["zuh"],
    "cim": ["cim"],
    "lan": ["lan"],
    "sot": ["st"],
    "lfa": ["lfa"],
    "tio": ["tio"],
    "mdr": ["mdr"],
    "ydd": ["ydd"],
    "nod": ["nod"],
    "ind": ["id"],
    "bhs": ["bhs"],
    "udg": ["udg"],
    "gou": ["gou"],
    "hre": ["hre"],
    "ahk": ["ahk"],
    "bis": ["bi"],
    "qvh": ["qvh"],
    "mfj": ["mfj"],
    "miy": ["miy"],
    "mgm": ["mgm"],
    "ybh": ["ybh"],
    "ymp": ["ymp"],
    "fal": ["fal"],
    "pex": ["pex"],
    "bfd": ["bfd"],
    "zho": ["zh", "zh-CN"],
    "pwg": ["pwg"],
    "bgf": ["bgf"],
    "omw": ["omw"],
    "dtr": ["dtr"],
    "kur": ["ku"],
    "cak": ["cak"],
    "kir": ["ky"],
    "sgd": ["sgd"],
    "quc": ["quc"],
    "cuh": ["cuh"],
    "eee": ["eee"],
    "bze": ["bze"],
    "bod": ["bo"],
    "jmx": ["jmx-x-smp", "jmx", "jmx-x-EnAm", "jmx-x-coi"],
    "new": ["new"],
    "dig": ["dig"],
    "guj": ["gu"],
    "dug": ["dug"],
    "pag": ["pag"],
    "aaa": ["aaa"],
    "bag": ["bag"],
    "oji": ["oj"],
    "ngn": ["ngn"],
    "nya": ["ny"],
    "zlm": ["zlm"],
    "kbq": ["kbq"],
    "baw": ["baw"],
    "aka": ["ak"],
    "mot": ["mot"],
    "amu": ["amu"],
    "tam": ["ta"],
    "tgk": ["tg"],
    "nlv": ["nlv"],
    "aph": ["aph"],
    "mlk": ["mlk"],
    "eng": ["en-Brai-IN-x-Chetana-Trust", "en-Dupl", "en-IN", "en"],
    "dje": ["dje"],
    "nyu": ["nyu"],
    "tnl": ["tnl"],
    "xkg": ["xkg"],
    "gbj": ["gbj"],
    "snk": ["snk-Arab", "snk"],
    "ino": ["ino"],
    "sox": ["sox"],
    "tpu": ["tpu"],
    "bya": ["bya"],
    "pmf": ["pmf"],
    "krr": ["krr"],
    "nuj": ["nuj"],
    "kan": ["kn"],
    "nep": ["ne"],
    "mgg": ["mgg"],
    "pkb": ["pkb"],
    "snl": ["snl"],
    "mgo": ["mgo"],
    "khm": ["km"],
    "kmg": ["kmg"],
    "mkz": ["mkz"],
    "bkc": ["bkc"],
    "pea": ["pea"],
    "mnw": ["mnw"],
    "msb": ["msb"],
    "lhu": ["lhu"],
    "tpl": ["tpl"],
    "ybi": ["ybi"],
    "bqm": ["bqm"],
    "uzb": ["uz"],
    "zul": ["zu"],
    "hin": ["hi"],
    "kwx": ["kwx"],
    "ike": ["ike"],
    "njy": ["njy"],
    "yav": ["yav"],
    "nge": ["nge"],
    "nxa": ["nxa"],
    "nxl": ["nxl"],
    "ybb": ["ybb"],
    "tdc": ["tdc"],
    "bcc": ["bcc"],
    "kbx": ["kbx"],
    "chp": ["chp"],
    "rme": ["rme"],
    "pis": ["pis"],
    "sdk": ["sdk"],
    "abc": ["abc"],
    "zaw": ["zaw"],
    "mle": ["mle"],
    "kby": ["kby"],
    "bbk": ["bbk"],
    "hro": ["hro"],
    "kvt": ["kvt"],
    "tnp": ["tnp"],
    "kak": ["kak"],
    "nwi": ["nwi"],
    "xho": ["xh"],
    "lbr": ["lbr"],
    "fon": ["fon"],
    "dag": ["dag"],
    "bim": ["bim"],
    "qve": ["qve"],
    "vie": ["vi"],
    "wnk": ["wnk"],
    "mqj": ["mqj"],
    "ags": ["ags"],
    "nsp": ["nsp"],
    "urd": ["ur"],
    "lgr": ["lgr"],
    "war": ["war"],
    "por": ["pt"],
    "lgg": ["lgg"],
    "loh": ["loh"],
    "tnt": ["tnt"],
    "cgc": ["cgc"],
    "thy": ["thy"],
    "luy": ["luy"],
    "aeu": ["aeu"],
    "kek": ["kek"],
    "tdg": ["tdg"],
    "sml": ["sml"],
    "tkd": ["tkd"],
    "sat": ["sat"],
    "nso": ["nso"],
    "bce": ["bce"],
    "dmg": ["dmg"],
    "bjr": ["bjr"],
    "hil": ["hil"],
    "gal": ["gal"],
    "fra": ["fr"],
    "ssn": ["ssn"],
    "mar": ["mr"],
    "ame": ["ame"],
    "kik": ["ki"],
    "hig": ["hig"],
    "myk": ["myk"],
    "qvm": ["qvm"],
    "pdu": ["pdu"],
    "sor": ["sor"],
    "enc": ["enc"],
    "nsn": ["nsn"],
    "mlw": ["mlw"],
    "jpn": ["ja"],
    "mry": ["mry"],
    "nco": ["nco"],
    "bss": ["bss"],
    "fli": ["fli"],
    "nza": ["nza"],
    "stk": ["stk"],
    "bwt": ["bwt"],
    "yid": ["yi"],
    "roo": ["roo"],
    "kau": ["kr"],
    "rel": ["rel"],
    "mrn": ["mrn"],
    "amp": ["amp"],
    "nwe": ["nwe"],
    "kqr": ["kqr"],
    "kjb": ["kjb"],
    "hna": ["hna"],
    "xmd": ["xmd"],
    "mai": ["mai"],
    "lts": ["lts"],
    "bho": ["bho"],
    "jra": ["jra"],
    "qvo": ["qvo"],
    "cuv": ["cuv"],
    "bkh": ["bkh"],
    "mmu": ["mmu"],
    "kin": ["rw"],
    "agq": ["agq"],
    "wbm": ["wbm"],
    "kam": ["kam"],
    "buo": ["buo"],
    "bud": ["bud"],
    "azn": ["azn"],
    "yea": ["yea"],
    "mgq": ["mgq"],
    "cmn": ["cmn"],
    "pae": ["pae"],
    "bri": ["bri"],
    "bkx": ["bkx"],
    "idt": ["idt"],
    "mfh": ["mfh"],
    "lsi": ["lsi"],
    "xty": ["xty"],
    "cbr": ["cbr"],
    "tsb": ["tsb"],
    "brb": ["brb"],
    "guc": ["guc"],
    "qxh": ["qxh"],
    "fuh": ["fuh"],
    "pce": ["pce"],
    "tuv": ["tuv"],
    "awb": ["awb"],
    "mam": ["mam"],
    "nst": ["nst"],
    "bam": ["bm"],
    "hao": ["hao"],
    "nla": ["nla"],
    "wtk": ["wtk"],
    "odk": ["odk"],
    "tom": ["tom"],
    "thl": ["thl"],
    "tuz": ["tuz"],
    "ewo": ["ewo"],
    "azo": ["azo"],
    "aia": ["aia"],
    "dnw": ["dnw"],
    "tpi": ["tpi"],
    "nyo": ["nyo"],
    "nas": ["nas"],
    "llg": ["llg"],
    "mxl": ["mxl"],
    "tbj": ["tbj"],
    "muv": ["muv"],
    "lns": ["lns"],
    "qaa": ["qaa"],
    "bwx": ["bwx"],
    "kor": ["ko"],
    "yin": ["yin"],
    "nhx": ["nhx"],
    "sxb": ["sxb"],
    "kwu": ["kwu"],
    "ita": ["it"],
    "rnl": ["rnl"],
    "tod": ["tod"],
    "thk": ["thk"],
    "unr": ["unr"],
    "nld": ["nl"],
    "ozm": ["ozm"],
    "bax": ["bax"],
    "quz": ["quz"],
}

# unique alpha3 codes. 376 in total
_BLOOM_LANGUAGES_ALPHA3 = {
    "kwd",
    "urd",
    "sps",
    "cry",
    "wms",
    "aka",
    "gwc",
    "bfn",
    "kms",
    "oki",
    "quf",
    "oji",
    "wni",
    "laj",
    "kyq",
    "rue",
    "mve",
    "gsw",
    "ken",
    "ekm",
    "swh",
    "tdt",
    "kmr",
    "syw",
    "xog",
    "uzb",
    "sot",
    "ksw",
    "pan",
    "zho",
    "pcg",
    "guz",
    "khb",
    "rus",
    "clo",
    "kik",
    "bob",
    "pbt",
    "teo",
    "kxp",
    "tet",
    "bis",
    "mxu",
    "lug",
    "cmo",
    "bef",
    "kan",
    "guj",
    "bzi",
    "mzm",
    "yas",
    "bec",
    "xho",
    "awa",
    "bkm",
    "tnn",
    "the",
    "ann",
    "myx",
    "ddg",
    "yet",
    "hbb",
    "adq",
    "sok",
    "bfm",
    "bra",
    "eng",
    "ilo",
    "lhm",
    "rug",
    "lmp",
    "hin",
    "mnf",
    "tdb",
    "ada",
    "tvs",
    "wbr",
    "dtp",
    "pnz",
    "sea",
    "brv",
    "xmg",
    "mne",
    "lwl",
    "tsn",
    "dty",
    "chd",
    "vif",
    "lkb",
    "ded",
    "nsk",
    "fub",
    "mhx",
    "mal",
    "isu",
    "bjn",
    "nya",
    "boz",
    "zgh",
    "bxa",
    "qub",
    "hla",
    "jgo",
    "taj",
    "ajz",
    "bod",
    "kau",
    "vie",
    "kmu",
    "psp",
    "xmm",
    "mar",
    "shn",
    "ron",
    "zuh",
    "cim",
    "lan",
    "lfa",
    "lao",
    "tio",
    "mdr",
    "ydd",
    "fil",
    "nod",
    "udg",
    "bhs",
    "gou",
    "hre",
    "ahk",
    "qvh",
    "zul",
    "mfj",
    "miy",
    "mgm",
    "ybh",
    "ymp",
    "fal",
    "pex",
    "bfd",
    "pwg",
    "bgf",
    "omw",
    "dtr",
    "cak",
    "sgd",
    "quc",
    "cuh",
    "eee",
    "bze",
    "new",
    "dig",
    "dug",
    "pag",
    "aaa",
    "bag",
    "ngn",
    "zlm",
    "yid",
    "kbq",
    "baw",
    "mot",
    "fra",
    "kor",
    "jmx",
    "amu",
    "nlv",
    "aph",
    "mlk",
    "afr",
    "amh",
    "dje",
    "enb",
    "nyu",
    "tnl",
    "xkg",
    "gbj",
    "ind",
    "ino",
    "jpn",
    "sox",
    "tpu",
    "bya",
    "pmf",
    "krr",
    "nuj",
    "por",
    "mgg",
    "pkb",
    "snl",
    "mgo",
    "kin",
    "kmg",
    "bam",
    "mkz",
    "bkc",
    "pea",
    "mnw",
    "msb",
    "lhu",
    "tpl",
    "ybi",
    "bqm",
    "kwx",
    "ike",
    "njy",
    "yav",
    "nge",
    "nxa",
    "nxl",
    "ybb",
    "tdc",
    "bcc",
    "kbx",
    "chp",
    "rme",
    "pis",
    "snk",
    "sdk",
    "abc",
    "zaw",
    "mle",
    "kby",
    "ceb",
    "bbk",
    "hro",
    "kvt",
    "tnp",
    "kak",
    "nwi",
    "lbr",
    "fon",
    "dag",
    "hat",
    "ben",
    "bim",
    "kur",
    "qve",
    "wnk",
    "mqj",
    "ags",
    "nsp",
    "lgr",
    "war",
    "lgg",
    "loh",
    "tnt",
    "cgc",
    "khm",
    "thy",
    "luy",
    "hau",
    "aeu",
    "kek",
    "tdg",
    "sml",
    "tkd",
    "sat",
    "nso",
    "tha",
    "bce",
    "dmg",
    "bjr",
    "tam",
    "hil",
    "gal",
    "ssn",
    "saq",
    "ame",
    "hig",
    "myk",
    "qvm",
    "swa",
    "pdu",
    "sor",
    "enc",
    "nsn",
    "mlw",
    "ita",
    "mry",
    "nco",
    "ori",
    "bss",
    "tgk",
    "fli",
    "nza",
    "stk",
    "nld",
    "bwt",
    "roo",
    "csw",
    "rel",
    "mrn",
    "amp",
    "nwe",
    "kqr",
    "kjb",
    "hna",
    "xmd",
    "deu",
    "mai",
    "lts",
    "bho",
    "jra",
    "qvo",
    "cuv",
    "bkh",
    "mmu",
    "tso",
    "ven",
    "spa",
    "nep",
    "agq",
    "wbm",
    "kam",
    "buo",
    "bud",
    "azn",
    "yea",
    "fas",
    "mgq",
    "cmn",
    "pae",
    "bri",
    "bkx",
    "idt",
    "mfh",
    "lsi",
    "xty",
    "cbr",
    "tsb",
    "brb",
    "guc",
    "som",
    "qxh",
    "kir",
    "fuh",
    "pce",
    "tuv",
    "awb",
    "mam",
    "nst",
    "hao",
    "nla",
    "wtk",
    "odk",
    "mya",
    "san",
    "tom",
    "thl",
    "tuz",
    "ewo",
    "azo",
    "aia",
    "dnw",
    "tpi",
    "nyo",
    "nas",
    "llg",
    "fuv",
    "mxl",
    "tbj",
    "muv",
    "lns",
    "qaa",
    "bwx",
    "yin",
    "nhx",
    "sxb",
    "kwu",
    "rnl",
    "tod",
    "thk",
    "unr",
    "ozm",
    "bax",
    "quz",
}

# Languages that have stories that aren't quarantined 353 in total
_BLOOM_LANGUAGES_ALPHA3_VALID = [
    "kwd",
    "urd",
    "sps",
    "wms",
    "aka",
    "gwc",
    "bfn",
    "kms",
    "oki",
    "quf",
    "oji",
    "wni",
    "laj",
    "kyq",
    "rue",
    "mve",
    "gsw",
    "ken",
    "ekm",
    "tdt",
    "syw",
    "xog",
    "uzb",
    "sot",
    "ksw",
    "pan",
    "zho",
    "pcg",
    "guz",
    "khb",
    "rus",
    "clo",
    "kik",
    "bob",
    "pbt",
    "teo",
    "kxp",
    "tet",
    "bis",
    "mxu",
    "lug",
    "cmo",
    "bef",
    "kan",
    "guj",
    "bzi",
    "mzm",
    "yas",
    "bec",
    "xho",
    "awa",
    "bkm",
    "tnn",
    "the",
    "ann",
    "myx",
    "ddg",
    "yet",
    "hbb",
    "adq",
    "bfm",
    "bra",
    "eng",
    "ilo",
    "lhm",
    "rug",
    "lmp",
    "hin",
    "mnf",
    "tdb",
    "ada",
    "tvs",
    "wbr",
    "dtp",
    "pnz",
    "sea",
    "brv",
    "xmg",
    "mne",
    "lwl",
    "tsn",
    "dty",
    "chd",
    "vif",
    "lkb",
    "ded",
    "nsk",
    "fub",
    "mhx",
    "mal",
    "isu",
    "bjn",
    "nya",
    "boz",
    "bxa",
    "qub",
    "hla",
    "jgo",
    "taj",
    "ajz",
    "bod",
    "kau",
    "vie",
    "kmu",
    "xmm",
    "mar",
    "shn",
    "ron",
    "zuh",
    "cim",
    "lan",
    "lfa",
    "tio",
    "mdr",
    "ydd",
    "fil",
    "nod",
    "udg",
    "bhs",
    "gou",
    "hre",
    "ahk",
    "qvh",
    "zul",
    "mfj",
    "miy",
    "mgm",
    "ybh",
    "ymp",
    "pex",
    "bfd",
    "pwg",
    "bgf",
    "omw",
    "dtr",
    "cak",
    "sgd",
    "quc",
    "cuh",
    "bze",
    "new",
    "dig",
    "dug",
    "pag",
    "aaa",
    "bag",
    "ngn",
    "zlm",
    "yid",
    "kbq",
    "baw",
    "mot",
    "fra",
    "kor",
    "jmx",
    "amu",
    "nlv",
    "aph",
    "mlk",
    "afr",
    "amh",
    "dje",
    "enb",
    "nyu",
    "tnl",
    "xkg",
    "gbj",
    "ind",
    "ino",
    "jpn",
    "sox",
    "tpu",
    "bya",
    "pmf",
    "krr",
    "nuj",
    "por",
    "mgg",
    "pkb",
    "snl",
    "mgo",
    "kin",
    "kmg",
    "bam",
    "mkz",
    "bkc",
    "pea",
    "mnw",
    "msb",
    "lhu",
    "tpl",
    "ybi",
    "bqm",
    "njy",
    "yav",
    "nge",
    "nxa",
    "nxl",
    "ybb",
    "bcc",
    "kbx",
    "chp",
    "pis",
    "snk",
    "sdk",
    "abc",
    "zaw",
    "mle",
    "kby",
    "ceb",
    "bbk",
    "hro",
    "tnp",
    "kak",
    "nwi",
    "lbr",
    "fon",
    "dag",
    "hat",
    "ben",
    "kur",
    "qve",
    "wnk",
    "mqj",
    "ags",
    "lgr",
    "war",
    "lgg",
    "loh",
    "tnt",
    "cgc",
    "khm",
    "luy",
    "hau",
    "aeu",
    "kek",
    "tdg",
    "sml",
    "tkd",
    "sat",
    "nso",
    "tha",
    "bce",
    "dmg",
    "bjr",
    "tam",
    "hil",
    "gal",
    "ssn",
    "saq",
    "ame",
    "hig",
    "myk",
    "qvm",
    "swa",
    "pdu",
    "enc",
    "nsn",
    "mlw",
    "ita",
    "mry",
    "nco",
    "ori",
    "bss",
    "tgk",
    "fli",
    "nza",
    "stk",
    "nld",
    "bwt",
    "roo",
    "csw",
    "rel",
    "mrn",
    "amp",
    "nwe",
    "kqr",
    "kjb",
    "hna",
    "xmd",
    "deu",
    "mai",
    "lts",
    "bho",
    "jra",
    "qvo",
    "cuv",
    "bkh",
    "mmu",
    "tso",
    "ven",
    "spa",
    "nep",
    "kam",
    "agq",
    "wbm",
    "buo",
    "bud",
    "azn",
    "yea",
    "fas",
    "mgq",
    "pae",
    "bri",
    "bkx",
    "idt",
    "mfh",
    "lsi",
    "xty",
    "cbr",
    "tsb",
    "brb",
    "guc",
    "som",
    "qxh",
    "kir",
    "fuh",
    "pce",
    "tuv",
    "awb",
    "mam",
    "nst",
    "hao",
    "nla",
    "wtk",
    "odk",
    "mya",
    "san",
    "tom",
    "thl",
    "tuz",
    "ewo",
    "azo",
    "aia",
    "dnw",
    "tpi",
    "nyo",
    "nas",
    "llg",
    "tbj",
    "lns",
    "qaa",
    "bwx",
    "nhx",
    "sxb",
    "kwu",
    "rnl",
    "tod",
    "thk",
    "unr",
    "ozm",
    "bax",
    "quz",
]


def split_stories_into_train_val_test(
    story_ids,
    test_size_max_threshold=50,
    test_size_max_proportion=0.1,
    train_size_max_proportion=0.8,
):
    splits = []

    story_ids.sort()  # it's a list of uuid4 values. This is essentially a random shuffle, but deterministic.

    if len(story_ids) > test_size_max_threshold:
        test_size = max(
            test_size_max_threshold, int(len(story_ids) * test_size_max_proportion),
        )
    else:
        test_size = len(story_ids)
    if (len(story_ids) - test_size) > test_size_max_threshold:
        train_size = max(
            (len(story_ids) - test_size - test_size_max_threshold),
            int((len(story_ids) - test_size) * train_size_max_proportion),
        )
    else:
        train_size = len(story_ids) - test_size
    dev_size = len(story_ids) - train_size - test_size

    # make sure it's all nonzero...
    test_size = max(test_size, 0)
    dev_size = max(dev_size, 0)
    train_size = max(train_size, 0)

    test_list = []
    dev_list = []
    train_list = []
    for story_id in story_ids:
        if len(test_list) < test_size:
            test_list.append(story_id)
        elif len(dev_list) < dev_size:
            dev_list.append(story_id)
        else:
            train_list.append(story_id)

    # empty lists have a truthy value of false but I want to explicitly check the length for clarity
    if len(test_list) > 0:
        split_tuple = (datasets.Split.TEST, test_list)
        splits.append(split_tuple)

    if len(dev_list) > 0:
        split_tuple = (datasets.Split.VALIDATION, dev_list)
        splits.append(split_tuple)

    if len(train_list) > 0:
        split_tuple = (datasets.Split.TRAIN, train_list)
        splits.append(split_tuple)

    return splits


def get_story_ids_by_language(bloom_vist_dict):
    stories_by_language = defaultdict(list)
    stories_by_id = defaultdict(list)

    for single_element_list in bloom_vist_dict["annotations"]:
        annotation = single_element_list[0]
        story_id = annotation["story_id"]
        stories_by_id[story_id].append(single_element_list)

    for story_id in stories_by_id.keys():
        list_of_annotations_for_story = stories_by_id[story_id]

        # assuming this is consistent for the whole story, which it should be.
        langcode_for_story = list_of_annotations_for_story[0][0]["lang"]

        stories_by_language[langcode_for_story].append(
            story_id
        )  # now it's a list of lists

    # stories_by_language = list(set(stories_by_language))
    print(f"We have {len(stories_by_language.keys())} languages")
    return stories_by_language


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Take bloom downloads and output SIS JSON"
    )

    parser.add_argument(
        "path_to_bloom_vist_json",
        # dest="source",
        type=Path,
        default=Path(
            "dedupe_june22/bloom_vist_june15_deduped_june21_langfiltered_june22.json"
        ),
        help="json to split",
    )

    parser.add_argument(
        "--output_folder",
        # dest="source",
        type=Path,
        default=Path("splitting/"),
        help="json to split",
    )

    args = parser.parse_args()
    with open(str(args.path_to_bloom_vist_json)) as bvf:
        bloom_vist_dict = json.load(bvf)

    print(bloom_vist_dict.keys())
    output_folder = Path(args.output_folder)
    output_folder.mkdir(exist_ok=True, parents=True)

    stories_by_lang = get_story_ids_by_language(bloom_vist_dict)
    # print(stories_by_lang)
    for lang in list(stories_by_lang)[:3]:
        stories_for_lang = list(set(stories_by_lang[lang]))

        print(f"{lang} has {len(stories_for_lang)} stories")

        splits = split_stories_into_train_val_test(stories_for_lang)

        for name, split_story_ids in splits:
            print(f"{lang} has {len(split_story_ids)} in {name}")
            split_copy = copy.deepcopy(bloom_vist_dict)
            split_copy["annotations"] = []
            split_copy["images"] = []

            split_copy["albums"] = []
            split_image_ids_to_keep = []
            album_ids_to_keep = []

            for annotation in bloom_vist_dict["annotations"]:
                if annotation[0]["story_id"] in split_story_ids:
                    split_copy["annotations"].append(annotation)
                    split_image_ids_to_keep.append(annotation[0]["photo_flickr_id"])
                    album_ids_to_keep.append(annotation[0]["album_id"])

            split_image_ids_to_keep = list(set(split_image_ids_to_keep))
            for image in bloom_vist_dict["images"]:
                if image["id"] in split_image_ids_to_keep:
                    split_copy["images"].append(image)

            album_ids_to_keep = list(set(album_ids_to_keep))
            for album in bloom_vist_dict["albums"]:
                if album["id"] in album_ids_to_keep:
                    split_copy["albums"].append(album)

            output_json_path = (
                output_folder
                / f"{args.path_to_bloom_vist_json.stem }_{lang}_{name}.json"
            )

            with open(output_json_path, "w") as out_file:
                json.dump(split_copy, out_file)
